# example workflow for Coverity thin client scans on CNC using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: cnc-sig-action

on:
  push:
    branches: [ main, master, stage, release ]
  pull_request:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.2.0
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_project_name: ${{ github.event.repository.name }}
        coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
        coverity_policy_view: 10014 # viewID for Outstanding Issues
    - name: Coverity PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.2.0
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_project_name: ${{ github.event.repository.name }}
        coverity_stream_name: ${{ github.event.repository.name }}-${{ github.base_ref }}
        coverity_automation_prcomment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
