# example workflow for Coverity Thin Client (CNC) scans using the Bridge CLI
name: cnc-bridge

on:
  push:
    branches: [ main, master, stage, release ]
  pull_request:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Coverity Scan
      env:
        BRIDGECLI_LINUX64: ${{ vars.BRIDGECLI_LINUX64 }}
      run: |
        curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/synopsys-bridge --verbose --stage connect \
            coverity.connect.url=${{ vars.COVERITY_URL }} \
            coverity.connect.user.name=${{ secrets.COVERITY_USER }} \
            coverity.connect.user.password=${{ secrets.COVERITY_PASSPHRASE }} \
            coverity.connect.project.name=${{ github.event.repository.name }} \
            coverity.connect.stream.name=${{ github.event.repository.name }}-${{ github.ref_name }} \
            coverity.connect.policy.view=10044 # viewID for Outstanding Issues
