# Coverity thin client with CNC scan farm on a GitHub-hosted ephemeral runner
name: cnc-thin-client

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest

    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COV_STREAM: hello-java-master
      BLDCMD: mvn -B compile

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Coverity Download
      run: |
        PLATFORM=linux64
        VERSION=2022.3.0
        curl -fLsS $COV_URL/api/v2/scans/downloads/cov_thin_client-$PLATFORM-$VERSION.tar.gz | tar -C $RUNNER_TEMP -xzf -

    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        export PATH=$PATH:$RUNNER_TEMP/bin
        export COVERITY_CLI_ANALYSIS_LOCATION=cloud
        export COVERITY_CLI_CLOUD_ANALYSIS_ASYNC=false
        coverity scan -o commit.connect.url=$COV_URL -o commit.connect.stream=$COV_STREAM -- $BLDCMD
