# example workflow for Coverity on Polaris using the open source community actions
# https://github.com/synopsys-sig-community/setup-polaris-analysis
# https://github.com/synopsys-sig-community/polaris-analysis
name: coverity-on-polaris-sarif
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Setup Polaris CLI
      uses: synopsys-sig-community/setup-polaris-analysis@main
      with:
        polaris_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_version: 2024.12.0
    - name: Coverity on Polaris Scan
      uses: synopsys-sig-community/polaris-analysis@main
      with:
        project: chuckaude-${{ github.event.repository.name }}
        polaris_config_overrides: --co project.name=chuckaude-${{ github.event.repository.name }}
        polaris_sarif: true
    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: polaris-scan-results.sarif.json
      continue-on-error: true
    - name: Archive SARIF Report
      uses: actions/upload-artifact@v4
      with:
        name: polaris-SARIF-report
        path: ${{ github.workspace }}/polaris-scan-results.sarif.json
      continue-on-error: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: polaris-cli-logs
#        path: ${{ github.workspace }}/.blackduck
