# Coverity on a self-hosted runner
name: coverity

on:
  push:
    branches: [ master, stage, 'releases/**' ]
  pull_request:
    branches: [ master, stage, 'releases/**' ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: self-hosted

    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_TOOL_HOME: /opt/coverity/analysis/current
      COVERITY_PROJECT: hello-java
      BLDCMD: mvn -B compile
      CHECKERS: --webapp-security

    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Coverity Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        export PATH=$PATH:$COVERITY_TOOL_HOME/bin
        cov-build --dir idir --fs-capture-search $GITHUB_WORKSPACE $BLDCMD
        cov-analyze --dir idir --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
        cov-commit-defects --dir idir --ticker-mode none --url $COV_URL --stream $COVERITY_PROJECT-${GITHUB_REF##*/} --scm git \
          --description $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID --target $RUNNER_OS --version $GITHUB_SHA

    - name: Coverity Quality Gate
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/OWASP%20Web%20Top%2010?projectId=$COVERITY_PROJECT > results.json
        if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi

    - id: changeset
      name: Get Pull Request Changeset
      uses: jitterbit/get-changed-files@v1
      if: ${{ github.event_name == 'pull_request' }}

    - name: Coverity Incremental Scan
      if: ${{ github.event_name == 'pull_request' && steps.changeset.outputs.added_modified != '' }}
      run: |
        export PATH=$PATH:$COVERITY_TOOL_HOME/bin
        cov-run-desktop --dir idir --url $COV_URL --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --build $BLDCMD
        cov-run-desktop --dir idir --url $COV_URL --stream $COVERITY_PROJECT-$GITHUB_BASE_REF --present-in-reference false \
          --ignore-uncapturable-inputs true --exit1-if-defects true ${{ steps.changeset.outputs.added_modified }}
