# example workflow for Polaris SaaS scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: polaris-sig-action
on:
  push:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      uses: synopsys-sig/synopsys-action@v1.0.0
      with:
        polaris_serverUrl: ${{ secrets.POLARIS_SERVERURL }}
        polaris_accessToken: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_application_name: chuckaude-${{ github.event.repository.name }}
        polaris_project_name: chuckaude-${{ github.event.repository.name }}
        polaris_assessment_types: "[\"SAST\", \"SCA\"]"
