# Example workflow for Polaris on public GitHub-hosted runners

name: Polaris public runner
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  polaris:

    runs-on: ubuntu-latest

    env:
      POLARIS_SERVER_URL:  https://sipse.polaris.synopsys.com/
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: System info
      run: |
        uname -a
        df -h
        env | sort
        ls -al $HOME
        ls -al $PWD
    - name: Polaris setup
      run: |
        wget -q $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -j polaris_cli-linux64.zip -d /tmp
        /tmp/polaris setup -p chuckaude-hello-java -e shell='mvn -B clean' -b shell='mvn -B compile'
        /tmp/polaris install
    - name: Polaris scan
      run: /tmp/polaris analyze -w
