# example workflow for Polaris scans using the Bridge CLI
name: polaris-bridge-cli
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: ubuntu-latest
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ vars.POLARIS_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_POLARIS_APPLICATION_NAME: chuckaude-${{ github.event.repository.name }}
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris
    - name: Polaris PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris \
            polaris.prcomment.enabled=true \
            polaris.branch.parent.name=${{ github.event.base_ref }} \
            github.repository.branch.name=${{ github.ref_name }} \
            github.repository.name=${{ github.event.repository.name }} \
            github.repository.owner.name=${{ github.repository_owner }} \
            github.repository.pull.number=${{ github.event.number }} \
            github.user.token=${{ secrets.GITHUB_TOKEN }}
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
