# example workflow for Polaris scans using the Bridge CLI
name: polaris-bridge-cli-win64
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      env:
        BRIDGE_POLARIS_SERVERURL: ${{ vars.POLARIS_SERVERURL }}
        BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
        BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
        BRIDGE_POLARIS_APPLICATION_NAME: chuckaude-${{ github.event.repository.name }}
        BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
        BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
      run: |
        Invoke-WebRequest -Uri ${{ vars.BRIDGECLI_WIN64 }} -OutFile bridge.zip
        Expand-Archive -Path bridge.zip -DestinationPath ${{ runner.temp }} -Force
        Remove-Item -Path bridge.zip -Force
        ${{ runner.temp }}/synopsys-bridge --verbose --stage polaris
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
