name: Polaris public runner
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  polaris:

    runs-on: ubuntu-latest

    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: hello-java
      BLDCMD: mvn -B package -DskipTests

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Polaris Scan
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=$PROJECT analyze -w -- $BLDCMD
