name: "SAST"
on:
  push:
    branches:
      - master
      - develop
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  Coverity:
    runs-on: self-hosted
    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PROJECT: hello-java
      COVHOME: /home/hugues/cov-analysis-linux64-2021.03
      BLDCMD: mvn clean compile
      CHECKERS: --all
 
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 15
 
    - name: Coverity Full Scan
      run: |
        set -x
        $COVHOME/bin/cov-configure --java
        $COVHOME/bin/cov-build --dir idir --fs-capture-search $GITHUB_WORKSPACE $BLDCMD
        $COVHOME/bin/cov-analyze --dir idir --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
        $COVHOME/bin/cov-commit-defects --dir idir --ticker-mode none --url $COV_URL --stream $COVERITY_PROJECT-${GITHUB_REF##*/} --scm git \
          --description $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID --target $RUNNER_OS --version $GITHUB_SHA
        $COVHOME/bin/cov-format-errors --dir idir --json-output-v8 cov-findings-v8.json
        $COVHOME/node/bin/node $COVHOME/SARIF/cov-format-sarif-for-github.js --inputFile cov-findings-v8.json --outputFile cov-findings-sarif.json --repoName hugues-martin/hello-java --checkoutPath hugues-martin/hello-java src $GITHUB_SHA
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
         # Path to SARIF file relative to the root of the repository
         sarif_file: results.sarif
